# Generated by Django 6.0.2 on 2026-02-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_post_publish_post_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Drafts'), ('PB', 'Published')], default='DF', max_length=2),
        ),
    ]
